#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Package-Stash-XS
Version  : 0.30
Release  : 23
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-XS-0.30.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-XS-0.30.tar.gz
Summary  : 'Faster and more correct implementation of the Package::Stash API'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Package-Stash-XS-license = %{version}-%{release}
Requires: perl-Package-Stash-XS-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Try::Tiny)

%description
This archive contains the distribution Package-Stash-XS,
version 0.30:
Faster and more correct implementation of the Package::Stash API

%package dev
Summary: dev components for the perl-Package-Stash-XS package.
Group: Development
Provides: perl-Package-Stash-XS-devel = %{version}-%{release}
Requires: perl-Package-Stash-XS = %{version}-%{release}

%description dev
dev components for the perl-Package-Stash-XS package.


%package license
Summary: license components for the perl-Package-Stash-XS package.
Group: Default

%description license
license components for the perl-Package-Stash-XS package.


%package perl
Summary: perl components for the perl-Package-Stash-XS package.
Group: Default
Requires: perl-Package-Stash-XS = %{version}-%{release}

%description perl
perl components for the perl-Package-Stash-XS package.


%prep
%setup -q -n Package-Stash-XS-0.30
cd %{_builddir}/Package-Stash-XS-0.30

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Package-Stash-XS
cp %{_builddir}/Package-Stash-XS-0.30/LICENSE %{buildroot}/usr/share/package-licenses/perl-Package-Stash-XS/da781ad4cfead0df917de25fe475c39b124364ab
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Package::Stash::XS.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Package-Stash-XS/da781ad4cfead0df917de25fe475c39b124364ab

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
